ALTER TABLE jobs
    ADD COLUMN skip_screenshots  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN skip_images       BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN skip_phones       BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN skip_page_export  BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN skip_text_urls    BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN skip_qr           BOOLEAN NOT NULL DEFAULT FALSE;
