-- Borderless ("stream") table extraction becomes the shipping DEFAULT.
--
-- V8 added jobs.stream_tables as BOOLEAN NOT NULL DEFAULT FALSE, matching the flag's then-current
-- opt-in default. The product default is now ON (see PdfTitanArumApp.STREAM_TABLES_DEFAULT), so this
-- moves the COLUMN default to match. Migrations are append-only: V8 is left exactly as it shipped.
--
-- WHAT THIS DOES AND DOES NOT CHANGE. SET DEFAULT only affects INSERTs that OMIT the column. It
-- rewrites nothing:
--   * EXISTING ROWS KEEP THEIR STORED VALUE. A job submitted before this migration ran was submitted
--     under the old default and keeps the behaviour its submitter chose -- including a pending row
--     that a worker has not claimed yet. Pending work is therefore NOT silently re-interpreted by a
--     deploy; only jobs submitted after it get the new default.
--   * ApiRoutes always supplies the column explicitly, so this default is not what makes the REST
--     surface default-on (ApiRoutes' absent-form-field resolution does that). This default is the
--     backstop for INSERTs that omit the column, which in practice means an OLD APPLICATION BINARY
--     mid-rolling-deploy, or a hand-written/administrative INSERT.
--
-- ROLLING DEPLOY, both directions:
--   * DB ahead of app (this migration applied, old binary still running): the old binary's INSERT
--     omits stream_tables and now gets TRUE. That is the intended new default and is safe -- the old
--     binary reads the column back and honours whatever it holds. It does mean an old binary starts
--     producing default-on jobs as soon as the DB is migrated, which is exactly the flip being
--     deployed; roll it back with the ALTER at the bottom of this comment if that is not wanted yet.
--   * App ahead of DB (new binary, DB still at V8): the new binary always writes the column
--     explicitly, so it is unaffected by the column default and behaves correctly; Flyway will apply
--     this migration on its next start. No window in which writes fail.
--
-- To pin a deployment back to opt-in WITHOUT reverting code:
--   ALTER TABLE jobs ALTER COLUMN stream_tables SET DEFAULT FALSE;
-- (and set TITANARUM_STREAM_TABLES=0 for the blastbox workers, whose default does not come from
-- this table at all).
ALTER TABLE jobs
    ALTER COLUMN stream_tables SET DEFAULT TRUE;
